const ICD10_LIST = [
  // 傳染病
  { code: "A00.0", name_zh: "霍亂弧菌所致的霍亂", name_en: "Cholera due to Vibrio cholerae 01, biovar cholerae" },
  { code: "A01.0", name_zh: "傷寒", name_en: "Typhoid fever" },
  { code: "A02.0", name_zh: "沙門氏菌腸炎", name_en: "Salmonella enteritis" },
  { code: "A04.1", name_zh: "腸道病原性大腸桿菌感染", name_en: "Enteropathogenic Escherichia coli infection" },
  { code: "A05.0", name_zh: "葡萄球菌性食物中毒", name_en: "Foodborne staphylococcal intoxication" },
  { code: "A06.0", name_zh: "急性阿米巴痢疾", name_en: "Acute amoebic dysentery" },
  { code: "A08.0", name_zh: "輪狀病毒性腸炎", name_en: "Rotaviral enteritis" },
  { code: "A09", name_zh: "感染性腸炎及結腸炎", name_en: "Infectious gastroenteritis and colitis" },
  { code: "A15.0", name_zh: "肺結核", name_en: "Tuberculosis of lung" },
  { code: "A36.0", name_zh: "咽白喉", name_en: "Pharyngeal diphtheria" },
  { code: "A37.0", name_zh: "百日咳", name_en: "Whooping cough due to Bordetella pertussis" },
  { code: "A38", name_zh: "猩紅熱", name_en: "Scarlet fever" },
  { code: "A40.0", name_zh: "A族鏈球菌所致的敗血症", name_en: "Sepsis due to streptococcus, group A" },
  { code: "A41.0", name_zh: "金黃色葡萄球菌所致的敗血症", name_en: "Sepsis due to Staphylococcus aureus" },
  { code: "A41.9", name_zh: "敗血症", name_en: "Sepsis, unspecified organism" },
  { code: "A49.0", name_zh: "葡萄球菌感染", name_en: "Staphylococcal infection, unspecified site" },
  { code: "A49.1", name_zh: "鏈球菌感染", name_en: "Streptococcal infection, unspecified site" },
  { code: "A63.0", name_zh: "肛門生殖器疣", name_en: "Anogenital warts" },
  { code: "A69.2", name_zh: "萊姆病", name_en: "Lyme disease" },
  { code: "A80.9", name_zh: "急性脊髓灰質炎", name_en: "Acute poliomyelitis, unspecified" },
  // 病毒性疾病
  { code: "B00.1", name_zh: "單純疱疹病毒性腦炎", name_en: "Herpesviral encephalitis" },
  { code: "B01.9", name_zh: "水痘", name_en: "Varicella without complication" },
  { code: "B02.9", name_zh: "帶狀疱疹", name_en: "Zoster without complications" },
  { code: "B05.9", name_zh: "麻疹", name_en: "Measles without complication" },
  { code: "B06.9", name_zh: "德國麻疹", name_en: "Rubella without complication" },
  { code: "B07", name_zh: "病毒性疣", name_en: "Viral warts" },
  { code: "B15.9", name_zh: "A型肝炎", name_en: "Acute hepatitis A without hepatic coma" },
  { code: "B16.9", name_zh: "急性B型肝炎", name_en: "Acute hepatitis B without delta-agent and without hepatic coma" },
  { code: "B17.1", name_zh: "急性C型肝炎", name_en: "Acute hepatitis C" },
  { code: "B18.1", name_zh: "慢性B型肝炎", name_en: "Chronic viral hepatitis B without delta-agent" },
  { code: "B18.2", name_zh: "慢性C型肝炎", name_en: "Chronic viral hepatitis C" },
  { code: "B20", name_zh: "人類免疫缺陷病毒感染（HIV）", name_en: "HIV disease" },
  { code: "B34.9", name_zh: "病毒感染", name_en: "Viral infection, unspecified" },
  { code: "B37.0", name_zh: "口腔念珠菌病", name_en: "Candidal stomatitis" },
  { code: "B37.3", name_zh: "外陰陰道念珠菌病", name_en: "Candidiasis of vulva and vagina" },
  // 腫瘤
  { code: "C00.9", name_zh: "唇惡性腫瘤", name_en: "Malignant neoplasm of lip, unspecified" },
  { code: "C02.9", name_zh: "舌惡性腫瘤", name_en: "Malignant neoplasm of tongue, unspecified" },
  { code: "C15.9", name_zh: "食道惡性腫瘤", name_en: "Malignant neoplasm of oesophagus, unspecified" },
  { code: "C16.9", name_zh: "胃惡性腫瘤", name_en: "Malignant neoplasm of stomach, unspecified" },
  { code: "C18.9", name_zh: "結腸惡性腫瘤", name_en: "Malignant neoplasm of colon, unspecified" },
  { code: "C19", name_zh: "直腸乙狀結腸交接處惡性腫瘤", name_en: "Malignant neoplasm of rectosigmoid junction" },
  { code: "C20", name_zh: "直腸惡性腫瘤", name_en: "Malignant neoplasm of rectum" },
  { code: "C22.0", name_zh: "肝細胞癌", name_en: "Liver cell carcinoma" },
  { code: "C25.9", name_zh: "胰臟惡性腫瘤", name_en: "Malignant neoplasm of pancreas, unspecified" },
  { code: "C32.9", name_zh: "喉惡性腫瘤", name_en: "Malignant neoplasm of larynx, unspecified" },
  { code: "C34.1", name_zh: "上葉肺惡性腫瘤", name_en: "Malignant neoplasm of upper lobe, bronchus or lung" },
  { code: "C34.9", name_zh: "肺惡性腫瘤", name_en: "Malignant neoplasm of bronchus and lung, unspecified" },
  { code: "C43.9", name_zh: "惡性黑色素瘤", name_en: "Malignant melanoma of skin, unspecified" },
  { code: "C50.9", name_zh: "乳房惡性腫瘤", name_en: "Malignant neoplasm of breast, unspecified" },
  { code: "C53.9", name_zh: "子宮頸惡性腫瘤", name_en: "Malignant neoplasm of cervix uteri, unspecified" },
  { code: "C54.1", name_zh: "子宮內膜惡性腫瘤", name_en: "Malignant neoplasm of endometrium" },
  { code: "C56.9", name_zh: "卵巢惡性腫瘤", name_en: "Malignant neoplasm of ovary" },
  { code: "C61", name_zh: "前列腺惡性腫瘤", name_en: "Malignant neoplasm of prostate" },
  { code: "C64.9", name_zh: "腎臟惡性腫瘤", name_en: "Malignant neoplasm of kidney, except renal pelvis" },
  { code: "C67.9", name_zh: "膀胱惡性腫瘤", name_en: "Malignant neoplasm of bladder, unspecified" },
  { code: "C71.9", name_zh: "腦惡性腫瘤", name_en: "Malignant neoplasm of brain, unspecified" },
  { code: "C73", name_zh: "甲狀腺惡性腫瘤", name_en: "Malignant neoplasm of thyroid gland" },
  { code: "C80.1", name_zh: "惡性腫瘤（原發部位不明）", name_en: "Malignant neoplasm, unspecified" },
  { code: "C91.0", name_zh: "急性淋巴性白血病", name_en: "Acute lymphoblastic leukaemia" },
  { code: "C92.0", name_zh: "急性骨髓性白血病", name_en: "Acute myeloblastic leukaemia" },
  { code: "C95.0", name_zh: "急性白血病", name_en: "Acute leukaemia of unspecified cell type" },
  // 良性腫瘤
  { code: "D12.6", name_zh: "結腸息肉", name_en: "Benign neoplasm of colon, unspecified" },
  { code: "D25.9", name_zh: "子宮肌瘤", name_en: "Leiomyoma of uterus, unspecified" },
  { code: "D27.9", name_zh: "卵巢良性腫瘤", name_en: "Benign neoplasm of ovary" },
  // 血液疾病
  { code: "D50.9", name_zh: "缺鐵性貧血", name_en: "Iron deficiency anaemia, unspecified" },
  { code: "D51.0", name_zh: "維生素B12缺乏性貧血", name_en: "Vitamin B12 deficiency anaemia due to intrinsic factor deficiency" },
  { code: "D52.0", name_zh: "葉酸缺乏性貧血", name_en: "Dietary folate deficiency anaemia" },
  { code: "D55.0", name_zh: "G6PD缺乏性貧血", name_en: "Anaemia due to glucose-6-phosphate dehydrogenase deficiency" },
  { code: "D57.1", name_zh: "鐮刀型紅血球疾病", name_en: "Sickle-cell disease without crisis" },
  { code: "D64.9", name_zh: "貧血", name_en: "Anaemia, unspecified" },
  { code: "D65", name_zh: "瀰散性血管內凝血", name_en: "Disseminated intravascular coagulation" },
  { code: "D69.3", name_zh: "特發性血小板減少性紫癜", name_en: "Immune thrombocytopenic purpura" },
  // 內分泌疾病
  { code: "E03.9", name_zh: "甲狀腺功能低下症", name_en: "Hypothyroidism, unspecified" },
  { code: "E05.0", name_zh: "甲狀腺毒症（Graves病）", name_en: "Thyrotoxicosis with diffuse goitre" },
  { code: "E05.9", name_zh: "甲狀腺機能亢進", name_en: "Thyrotoxicosis, unspecified" },
  { code: "E06.3", name_zh: "自體免疫性甲狀腺炎", name_en: "Autoimmune thyroiditis" },
  { code: "E10.9", name_zh: "第一型糖尿病", name_en: "Type 1 diabetes mellitus without complications" },
  { code: "E11.9", name_zh: "第二型糖尿病", name_en: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", name_zh: "第二型糖尿病併高血糖", name_en: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E13.9", name_zh: "糖尿病", name_en: "Other specified diabetes mellitus without complications" },
  { code: "E14.9", name_zh: "糖尿病（未特指）", name_en: "Unspecified diabetes mellitus without complications" },
  { code: "E21.0", name_zh: "原發性副甲狀腺機能亢進", name_en: "Primary hyperparathyroidism" },
  { code: "E27.1", name_zh: "原發性腎上腺皮質功能不全", name_en: "Primary adrenocortical insufficiency" },
  { code: "E66.9", name_zh: "肥胖症", name_en: "Obesity, unspecified" },
  { code: "E78.0", name_zh: "高膽固醇血症", name_en: "Pure hypercholesterolaemia" },
  { code: "E78.5", name_zh: "高脂血症", name_en: "Hyperlipidaemia, unspecified" },
  { code: "E87.1", name_zh: "低血鈉症", name_en: "Hypo-osmolality and hyponatraemia" },
  { code: "E87.5", name_zh: "高鉀血症", name_en: "Hyperkalaemia" },
  { code: "E87.6", name_zh: "低鉀血症", name_en: "Hypokalaemia" },
  // 精神疾病
  { code: "F10.2", name_zh: "酒精依賴症候群", name_en: "Alcohol dependence syndrome" },
  { code: "F20.0", name_zh: "偏執型精神分裂症", name_en: "Paranoid schizophrenia" },
  { code: "F20.9", name_zh: "精神分裂症", name_en: "Schizophrenia, unspecified" },
  { code: "F31.9", name_zh: "雙相情感障礙", name_en: "Bipolar affective disorder, unspecified" },
  { code: "F32.9", name_zh: "憂鬱症", name_en: "Depressive episode, unspecified" },
  { code: "F33.9", name_zh: "重鬱症", name_en: "Recurrent depressive disorder, unspecified" },
  { code: "F40.1", name_zh: "社交恐懼症", name_en: "Social phobias" },
  { code: "F41.1", name_zh: "廣泛性焦慮症", name_en: "Generalised anxiety disorder" },
  { code: "F43.1", name_zh: "創傷後壓力症候群", name_en: "Post-traumatic stress disorder" },
  { code: "F50.0", name_zh: "神經性厭食症", name_en: "Anorexia nervosa" },
  { code: "F60.3", name_zh: "邊緣性人格障礙", name_en: "Emotionally unstable personality disorder" },
  { code: "F70", name_zh: "輕度智能障礙", name_en: "Mild intellectual disabilities" },
  { code: "F84.0", name_zh: "自閉症", name_en: "Childhood autism" },
  { code: "F90.0", name_zh: "注意力缺陷過動症（ADHD）", name_en: "Attention deficit disorder with hyperactivity" },
  // 神經系統疾病
  { code: "G20", name_zh: "帕金森氏症", name_en: "Parkinson disease" },
  { code: "G30.9", name_zh: "阿茲海默症", name_en: "Alzheimer disease, unspecified" },
  { code: "G35", name_zh: "多發性硬化症", name_en: "Multiple sclerosis" },
  { code: "G40.9", name_zh: "癲癇", name_en: "Epilepsy, unspecified" },
  { code: "G43.9", name_zh: "偏頭痛", name_en: "Migraine, unspecified" },
  { code: "G44.2", name_zh: "緊張性頭痛", name_en: "Tension-type headache" },
  { code: "G45.9", name_zh: "短暫性腦缺血發作", name_en: "Transient cerebral ischaemic attack, unspecified" },
  { code: "G47.0", name_zh: "睡眠障礙（失眠）", name_en: "Insomnia, unspecified" },
  { code: "G47.3", name_zh: "睡眠呼吸中止症", name_en: "Sleep apnoea" },
  { code: "G51.0", name_zh: "貝爾氏麻痺", name_en: "Bell palsy" },
  { code: "G54.2", name_zh: "頸神經根病變", name_en: "Cervical root disorders, not elsewhere classified" },
  { code: "G54.4", name_zh: "腰薦神經根病變", name_en: "Lumbosacral root disorders, not elsewhere classified" },
  { code: "G61.0", name_zh: "格林-巴利症候群", name_en: "Guillain-Barre syndrome" },
  // 眼部疾病
  { code: "H00.0", name_zh: "麥粒腫（針眼）", name_en: "Hordeolum externum" },
  { code: "H01.0", name_zh: "眼瞼炎", name_en: "Blepharitis" },
  { code: "H10.1", name_zh: "急性結膜炎", name_en: "Acute atopic conjunctivitis" },
  { code: "H10.3", name_zh: "急性結膜炎（未特指）", name_en: "Acute conjunctivitis, unspecified" },
  { code: "H11.0", name_zh: "翼狀贅片", name_en: "Pterygium" },
  { code: "H25.9", name_zh: "老年性白內障", name_en: "Senile cataract, unspecified" },
  { code: "H26.9", name_zh: "白內障", name_en: "Cataract, unspecified" },
  { code: "H33.0", name_zh: "視網膜剝離", name_en: "Retinal detachment with retinal break" },
  { code: "H35.0", name_zh: "背景性視網膜病變", name_en: "Background retinopathy and retinal vascular changes" },
  { code: "H40.1", name_zh: "原發性開角性青光眼", name_en: "Open-angle glaucoma" },
  { code: "H43.1", name_zh: "玻璃體積血", name_en: "Vitreous haemorrhage" },
  { code: "H52.1", name_zh: "近視", name_en: "Myopia" },
  { code: "H52.4", name_zh: "老花眼", name_en: "Presbyopia" },
  { code: "H54.4", name_zh: "單眼視力障礙", name_en: "Blindness, one eye, low vision other eye" },
  // 耳鼻喉疾病
  { code: "H60.9", name_zh: "外耳炎", name_en: "Otitis externa, unspecified" },
  { code: "H65.9", name_zh: "非化膿性中耳炎", name_en: "Nonsuppurative otitis media, unspecified" },
  { code: "H66.9", name_zh: "中耳炎", name_en: "Suppurative and unspecified otitis media" },
  { code: "H72.9", name_zh: "鼓膜穿孔", name_en: "Perforation of tympanic membrane, unspecified" },
  { code: "H81.0", name_zh: "梅尼爾氏症", name_en: "Meniere disease" },
  { code: "H81.4", name_zh: "良性陣發性眩暈", name_en: "Vertigo of central origin" },
  { code: "H83.3", name_zh: "耳鳴", name_en: "Noise effects on inner ear" },
  { code: "H90.3", name_zh: "雙耳感音神經性聽力損失", name_en: "Sensorineural hearing loss, bilateral" },
  { code: "H91.9", name_zh: "聽力喪失", name_en: "Hearing loss, unspecified" },
  // 循環系統疾病
  { code: "I10", name_zh: "原發性高血壓", name_en: "Essential (primary) hypertension" },
  { code: "I11.9", name_zh: "高血壓性心臟病", name_en: "Hypertensive heart disease without heart failure" },
  { code: "I13.0", name_zh: "高血壓性心臟及腎臟病", name_en: "Hypertensive heart and renal disease with heart failure" },
  { code: "I20.0", name_zh: "不穩定性心絞痛", name_en: "Unstable angina" },
  { code: "I20.9", name_zh: "心絞痛", name_en: "Angina pectoris, unspecified" },
  { code: "I21.0", name_zh: "前壁急性心肌梗塞", name_en: "Acute transmural myocardial infarction of anterior wall" },
  { code: "I21.4", name_zh: "急性心肌梗塞（非ST上升）", name_en: "Acute subendocardial myocardial infarction" },
  { code: "I21.9", name_zh: "急性心肌梗塞", name_en: "Acute myocardial infarction, unspecified" },
  { code: "I25.1", name_zh: "動脈粥狀硬化性心臟病", name_en: "Atherosclerotic heart disease of native coronary artery" },
  { code: "I25.5", name_zh: "缺血性心肌病變", name_en: "Ischaemic cardiomyopathy" },
  { code: "I34.0", name_zh: "二尖瓣逆流", name_en: "Mitral (valve) insufficiency" },
  { code: "I35.0", name_zh: "主動脈瓣狹窄", name_en: "Aortic (valve) stenosis" },
  { code: "I42.0", name_zh: "擴張性心肌病變", name_en: "Dilated cardiomyopathy" },
  { code: "I42.1", name_zh: "肥厚性梗阻性心肌病變", name_en: "Hypertrophic obstructive cardiomyopathy" },
  { code: "I44.2", name_zh: "完全性房室傳導阻滯", name_en: "Atrioventricular block, complete" },
  { code: "I46.9", name_zh: "心臟停止", name_en: "Cardiac arrest, unspecified" },
  { code: "I47.1", name_zh: "室上性心搏過速", name_en: "Supraventricular tachycardia" },
  { code: "I47.2", name_zh: "心室頻脈", name_en: "Ventricular tachycardia" },
  { code: "I48.0", name_zh: "陣發性心房顫動", name_en: "Paroxysmal atrial fibrillation" },
  { code: "I48.2", name_zh: "慢性心房顫動", name_en: "Chronic atrial fibrillation" },
  { code: "I49.9", name_zh: "心律不整", name_en: "Cardiac arrhythmia, unspecified" },
  { code: "I50.0", name_zh: "充血性心臟衰竭", name_en: "Congestive heart failure" },
  { code: "I50.9", name_zh: "心臟衰竭", name_en: "Heart failure, unspecified" },
  { code: "I61.9", name_zh: "腦出血", name_en: "Intracerebral haemorrhage, unspecified" },
  { code: "I63.9", name_zh: "腦梗塞", name_en: "Cerebral infarction, unspecified" },
  { code: "I64", name_zh: "腦中風", name_en: "Stroke, not specified as haemorrhage or infarction" },
  { code: "I69.3", name_zh: "腦梗塞後遺症", name_en: "Sequelae of cerebral infarction" },
  { code: "I70.0", name_zh: "主動脈粥狀硬化", name_en: "Atherosclerosis of aorta" },
  { code: "I71.2", name_zh: "主動脈瘤（胸腔）", name_en: "Thoracic aortic aneurysm, without rupture" },
  { code: "I71.4", name_zh: "主動脈瘤（腹腔）", name_en: "Abdominal aortic aneurysm, without rupture" },
  { code: "I73.0", name_zh: "雷諾氏症候群", name_en: "Raynaud syndrome" },
  { code: "I80.2", name_zh: "下肢深部靜脈血栓", name_en: "Phlebitis and thrombophlebitis of other deep vessels of lower extremities" },
  { code: "I82.4", name_zh: "深靜脈血栓形成", name_en: "Acute embolism and thrombosis of deep veins of lower extremity" },
  { code: "I83.9", name_zh: "靜脈曲張", name_en: "Varicose veins of lower extremities without ulcer or inflammation" },
  // 呼吸系統疾病
  { code: "J00", name_zh: "急性鼻咽炎（感冒）", name_en: "Acute nasopharyngitis [common cold]" },
  { code: "J01.9", name_zh: "急性鼻竇炎", name_en: "Acute sinusitis, unspecified" },
  { code: "J02.0", name_zh: "鏈球菌性咽炎", name_en: "Streptococcal pharyngitis" },
  { code: "J02.9", name_zh: "急性咽炎", name_en: "Acute pharyngitis, unspecified" },
  { code: "J03.9", name_zh: "急性扁桃腺炎", name_en: "Acute tonsillitis, unspecified" },
  { code: "J04.0", name_zh: "急性喉炎", name_en: "Acute laryngitis" },
  { code: "J06.9", name_zh: "急性上呼吸道感染", name_en: "Acute upper respiratory infection, unspecified" },
  { code: "J10.0", name_zh: "流感（已知流感病毒）", name_en: "Influenza due to identified seasonal influenza virus" },
  { code: "J11.0", name_zh: "流感", name_en: "Influenza with pneumonia, virus not identified" },
  { code: "J12.9", name_zh: "病毒性肺炎", name_en: "Viral pneumonia, unspecified" },
  { code: "J15.9", name_zh: "細菌性肺炎", name_en: "Unspecified bacterial pneumonia" },
  { code: "J18.0", name_zh: "支氣管性肺炎", name_en: "Bronchopneumonia, unspecified organism" },
  { code: "J18.9", name_zh: "肺炎", name_en: "Pneumonia, unspecified organism" },
  { code: "J20.9", name_zh: "急性支氣管炎", name_en: "Acute bronchitis, unspecified" },
  { code: "J22", name_zh: "急性下呼吸道感染", name_en: "Unspecified acute lower respiratory infection" },
  { code: "J30.0", name_zh: "血管舒縮性鼻炎", name_en: "Vasomotor rhinitis" },
  { code: "J30.1", name_zh: "花粉過敏性鼻炎", name_en: "Allergic rhinitis due to pollen" },
  { code: "J30.4", name_zh: "過敏性鼻炎", name_en: "Other seasonal allergic rhinitis" },
  { code: "J31.0", name_zh: "慢性鼻炎", name_en: "Chronic rhinitis" },
  { code: "J32.9", name_zh: "慢性鼻竇炎", name_en: "Chronic sinusitis, unspecified" },
  { code: "J33.0", name_zh: "鼻息肉", name_en: "Polyp of nasal cavity" },
  { code: "J35.0", name_zh: "慢性扁桃腺炎", name_en: "Chronic tonsillitis" },
  { code: "J37.0", name_zh: "慢性喉炎", name_en: "Chronic laryngitis" },
  { code: "J38.5", name_zh: "聲帶痙攣", name_en: "Laryngeal spasm" },
  { code: "J40", name_zh: "支氣管炎（未特指急慢性）", name_en: "Bronchitis, not specified as acute or chronic" },
  { code: "J41.0", name_zh: "單純慢性支氣管炎", name_en: "Simple chronic bronchitis" },
  { code: "J42", name_zh: "慢性支氣管炎", name_en: "Unspecified chronic bronchitis" },
  { code: "J43.9", name_zh: "肺氣腫", name_en: "Emphysema, unspecified" },
  { code: "J44.1", name_zh: "慢性阻塞性肺病（COPD）急性發作", name_en: "Chronic obstructive pulmonary disease with acute exacerbation" },
  { code: "J44.9", name_zh: "慢性阻塞性肺病（COPD）", name_en: "Chronic obstructive pulmonary disease, unspecified" },
  { code: "J45.0", name_zh: "過敏性哮喘", name_en: "Predominantly allergic asthma" },
  { code: "J45.9", name_zh: "氣喘", name_en: "Asthma, unspecified" },
  { code: "J46", name_zh: "氣喘重積狀態", name_en: "Status asthmaticus" },
  { code: "J70.1", name_zh: "急性及亞急性放射性肺炎", name_en: "Acute and subacute radiation pneumonitis" },
  { code: "J80", name_zh: "急性呼吸窘迫症候群（ARDS）", name_en: "Acute respiratory distress syndrome" },
  { code: "J81.0", name_zh: "急性肺水腫", name_en: "Acute pulmonary oedema" },
  { code: "J86.0", name_zh: "膿胸（伴有瘺管）", name_en: "Pyothorax with fistula" },
  { code: "J90", name_zh: "胸腔積液", name_en: "Pleural effusion, not elsewhere classified" },
  { code: "J93.1", name_zh: "自發性氣胸", name_en: "Other spontaneous pneumothorax" },
  { code: "J96.0", name_zh: "急性呼吸衰竭", name_en: "Acute respiratory failure" },
  { code: "J96.1", name_zh: "慢性呼吸衰竭", name_en: "Chronic respiratory failure" },
  { code: "J98.1", name_zh: "肺塌陷", name_en: "Pulmonary collapse" },
  // 消化系統疾病
  { code: "K02.9", name_zh: "齲齒", name_en: "Caries of dentine" },
  { code: "K04.0", name_zh: "牙髓炎", name_en: "Pulpitis" },
  { code: "K05.1", name_zh: "慢性牙齦炎", name_en: "Chronic gingivitis" },
  { code: "K08.1", name_zh: "牙齒脫落", name_en: "Loss of teeth due to accident" },
  { code: "K11.2", name_zh: "唾液腺炎", name_en: "Sialoadenitis" },
  { code: "K20", name_zh: "食道炎", name_en: "Oesophagitis" },
  { code: "K21.0", name_zh: "胃食道逆流（伴食道炎）", name_en: "Gastro-oesophageal reflux disease with oesophagitis" },
  { code: "K21.9", name_zh: "胃食道逆流", name_en: "Gastro-oesophageal reflux disease without oesophagitis" },
  { code: "K25.9", name_zh: "胃潰瘍", name_en: "Gastric ulcer, unspecified" },
  { code: "K26.9", name_zh: "十二指腸潰瘍", name_en: "Duodenal ulcer, unspecified" },
  { code: "K29.3", name_zh: "慢性表淺性胃炎", name_en: "Chronic superficial gastritis" },
  { code: "K29.5", name_zh: "慢性胃炎", name_en: "Chronic gastritis, unspecified" },
  { code: "K29.7", name_zh: "胃炎", name_en: "Gastritis, unspecified" },
  { code: "K30", name_zh: "功能性消化不良", name_en: "Functional dyspepsia" },
  { code: "K35.2", name_zh: "急性闌尾炎（伴腹膜炎）", name_en: "Acute appendicitis with peritonitis" },
  { code: "K35.8", name_zh: "急性闌尾炎", name_en: "Acute appendicitis, unspecified" },
  { code: "K37", name_zh: "闌尾炎", name_en: "Unspecified appendicitis" },
  { code: "K40.9", name_zh: "腹股溝疝氣", name_en: "Unilateral inguinal hernia, without obstruction or gangrene" },
  { code: "K41.9", name_zh: "股疝氣", name_en: "Unilateral femoral hernia, without obstruction or gangrene" },
  { code: "K44.9", name_zh: "橫膈疝氣", name_en: "Diaphragmatic hernia without obstruction or gangrene" },
  { code: "K46.9", name_zh: "腹疝氣", name_en: "Unspecified abdominal hernia without obstruction or gangrene" },
  { code: "K50.9", name_zh: "克隆氏症", name_en: "Crohn disease of small intestine, unspecified" },
  { code: "K51.9", name_zh: "潰瘍性結腸炎", name_en: "Ulcerative colitis, unspecified" },
  { code: "K52.9", name_zh: "非感染性胃腸炎及結腸炎", name_en: "Noninfective gastroenteritis and colitis, unspecified" },
  { code: "K57.3", name_zh: "大腸憩室疾病（無穿孔或膿瘍）", name_en: "Diverticular disease of large intestine without perforation or abscess" },
  { code: "K58.0", name_zh: "腸躁症（伴腹瀉）", name_en: "Irritable bowel syndrome with diarrhoea" },
  { code: "K58.9", name_zh: "腸躁症", name_en: "Irritable bowel syndrome without diarrhoea" },
  { code: "K59.0", name_zh: "便秘", name_en: "Constipation" },
  { code: "K59.1", name_zh: "功能性腹瀉", name_en: "Functional diarrhoea" },
  { code: "K62.5", name_zh: "肛門出血", name_en: "Haemorrhage of anus and rectum" },
  { code: "K64.9", name_zh: "痔瘡", name_en: "Unspecified haemorrhoids" },
  { code: "K70.3", name_zh: "酒精性肝硬化", name_en: "Alcoholic cirrhosis of liver" },
  { code: "K72.0", name_zh: "急性及亞急性肝衰竭", name_en: "Acute and subacute hepatic failure" },
  { code: "K72.1", name_zh: "慢性肝衰竭", name_en: "Chronic hepatic failure" },
  { code: "K73.9", name_zh: "慢性肝炎", name_en: "Chronic hepatitis, unspecified" },
  { code: "K74.6", name_zh: "肝硬化", name_en: "Other and unspecified cirrhosis of liver" },
  { code: "K75.0", name_zh: "肝膿瘍", name_en: "Abscess of liver" },
  { code: "K76.0", name_zh: "非酒精性脂肪肝", name_en: "Fatty (change of) liver, not elsewhere classified" },
  { code: "K80.1", name_zh: "膽囊炎（伴有膽結石）", name_en: "Calculus of gallbladder with other cholecystitis" },
  { code: "K80.5", name_zh: "膽道結石（不伴膽管炎）", name_en: "Calculus of bile duct without cholangitis or cholecystitis" },
  { code: "K81.0", name_zh: "急性膽囊炎", name_en: "Acute cholecystitis" },
  { code: "K81.1", name_zh: "慢性膽囊炎", name_en: "Chronic cholecystitis" },
  { code: "K83.0", name_zh: "膽管炎", name_en: "Cholangitis" },
  { code: "K85.9", name_zh: "急性胰臟炎", name_en: "Acute pancreatitis, unspecified" },
  { code: "K86.1", name_zh: "慢性胰臟炎", name_en: "Other chronic pancreatitis" },
  { code: "K91.0", name_zh: "腸梗阻（術後）", name_en: "Vomiting following gastrointestinal surgery" },
  { code: "K92.0", name_zh: "嘔血", name_en: "Haematemesis" },
  { code: "K92.1", name_zh: "黑色糞便", name_en: "Melaena" },
  { code: "K92.2", name_zh: "消化道出血", name_en: "Gastrointestinal haemorrhage, unspecified" },
  // 皮膚疾病
  { code: "L01.0", name_zh: "膿痂疹", name_en: "Impetigo" },
  { code: "L02.9", name_zh: "皮膚膿瘍", name_en: "Cutaneous abscess, unspecified" },
  { code: "L03.1", name_zh: "其他肢體蜂窩組織炎", name_en: "Cellulitis of other parts of limb" },
  { code: "L03.9", name_zh: "蜂窩組織炎", name_en: "Cellulitis, unspecified" },
  { code: "L20.9", name_zh: "異位性皮膚炎", name_en: "Atopic dermatitis, unspecified" },
  { code: "L21.0", name_zh: "頭皮脂漏性皮膚炎", name_en: "Seborrhoeic capitis" },
  { code: "L23.9", name_zh: "過敏性接觸性皮膚炎", name_en: "Allergic contact dermatitis, unspecified cause" },
  { code: "L24.9", name_zh: "刺激性接觸性皮膚炎", name_en: "Irritant contact dermatitis, unspecified cause" },
  { code: "L25.9", name_zh: "接觸性皮膚炎", name_en: "Unspecified contact dermatitis, unspecified cause" },
  { code: "L27.0", name_zh: "藥物引起的廣泛性皮疹", name_en: "Generalised skin eruption due to drugs and medicaments" },
  { code: "L30.9", name_zh: "皮膚炎", name_en: "Dermatitis, unspecified" },
  { code: "L40.0", name_zh: "尋常性乾癬", name_en: "Psoriasis vulgaris" },
  { code: "L40.9", name_zh: "乾癬", name_en: "Psoriasis, unspecified" },
  { code: "L41.0", name_zh: "玫瑰糠疹", name_en: "Parapsoriasis" },
  { code: "L50.0", name_zh: "過敏性蕁麻疹", name_en: "Allergic urticaria" },
  { code: "L50.9", name_zh: "蕁麻疹", name_en: "Urticaria, unspecified" },
  { code: "L60.0", name_zh: "嵌甲", name_en: "Ingrowing nail" },
  { code: "L63.9", name_zh: "斑禿（圓形禿）", name_en: "Alopecia areata, unspecified" },
  { code: "L64.9", name_zh: "雄性禿", name_en: "Androgenic alopecia, unspecified" },
  { code: "L70.0", name_zh: "粉刺（青春痘）", name_en: "Acne vulgaris" },
  { code: "L72.0", name_zh: "表皮囊腫", name_en: "Epidermal cyst" },
  { code: "L89.9", name_zh: "褥瘡（壓瘡）", name_en: "Pressure ulcer, unspecified stage" },
  { code: "L98.4", name_zh: "慢性皮膚潰瘍", name_en: "Non-pressure chronic ulcer of skin, not elsewhere classified" },
  // 肌肉骨骼疾病
  { code: "M05.9", name_zh: "類風濕性關節炎", name_en: "Rheumatoid arthritis, unspecified" },
  { code: "M06.9", name_zh: "類風濕性關節炎（血清陰性）", name_en: "Rheumatoid arthritis, unspecified" },
  { code: "M08.0", name_zh: "幼年型類風濕性關節炎", name_en: "Juvenile rheumatoid arthritis" },
  { code: "M10.9", name_zh: "痛風", name_en: "Gout, unspecified" },
  { code: "M13.9", name_zh: "關節炎", name_en: "Arthritis, unspecified" },
  { code: "M16.1", name_zh: "原發性髖關節炎", name_en: "Unilateral primary osteoarthritis of hip" },
  { code: "M17.1", name_zh: "原發性膝關節炎", name_en: "Unilateral primary gonarthrosis" },
  { code: "M19.9", name_zh: "退化性關節炎", name_en: "Osteoarthritis, unspecified site" },
  { code: "M32.9", name_zh: "系統性紅斑性狼瘡", name_en: "Systemic lupus erythematosus, unspecified" },
  { code: "M35.0", name_zh: "乾燥症候群（修格蘭氏症）", name_en: "Sicca syndrome (Sjogren)" },
  { code: "M41.9", name_zh: "脊椎側彎", name_en: "Scoliosis, unspecified" },
  { code: "M47.2", name_zh: "頸椎病（伴有神經根病變）", name_en: "Other spondylosis with radiculopathy" },
  { code: "M47.8", name_zh: "頸椎退化性疾病", name_en: "Other spondylosis" },
  { code: "M48.0", name_zh: "椎管狹窄", name_en: "Spinal stenosis" },
  { code: "M50.1", name_zh: "頸椎間盤疾患（伴神經根病變）", name_en: "Cervical disc disorder with radiculopathy" },
  { code: "M51.1", name_zh: "腰椎間盤突出（伴神經根病變）", name_en: "Lumbar and other intervertebral disc degeneration" },
  { code: "M54.2", name_zh: "頸神經痛", name_en: "Cervicalgia" },
  { code: "M54.4", name_zh: "坐骨神經痛", name_en: "Lumbago with sciatica" },
  { code: "M54.5", name_zh: "下背痛", name_en: "Low back pain" },
  { code: "M60.9", name_zh: "肌炎", name_en: "Myositis, unspecified" },
  { code: "M62.8", name_zh: "肌肉疾患", name_en: "Other specified disorders of muscle" },
  { code: "M65.9", name_zh: "腱鞘炎", name_en: "Synovitis and tenosynovitis, unspecified" },
  { code: "M70.1", name_zh: "滑囊炎（肘）", name_en: "Bursitis of hand" },
  { code: "M75.1", name_zh: "旋轉肌袖損傷", name_en: "Rotator cuff syndrome" },
  { code: "M75.5", name_zh: "肩峰下滑囊炎", name_en: "Bursitis of shoulder" },
  { code: "M76.6", name_zh: "跟腱炎", name_en: "Achilles tendinitis" },
  { code: "M77.1", name_zh: "網球肘（外上髁炎）", name_en: "Lateral epicondylitis" },
  { code: "M77.3", name_zh: "足跟骨刺", name_en: "Calcaneal spur" },
  { code: "M79.3", name_zh: "結節炎（纖維肌痛）", name_en: "Panniculitis, unspecified" },
  { code: "M80.0", name_zh: "停經後骨質疏鬆症（伴骨折）", name_en: "Postmenopausal osteoporosis with current pathological fracture" },
  { code: "M81.0", name_zh: "停經後骨質疏鬆症", name_en: "Postmenopausal osteoporosis" },
  { code: "M81.9", name_zh: "骨質疏鬆症", name_en: "Osteoporosis, unspecified" },
  // 泌尿系統疾病
  { code: "N00.9", name_zh: "急性腎炎症候群", name_en: "Acute nephritic syndrome, unspecified morphological changes" },
  { code: "N02.9", name_zh: "復發性及持續性血尿", name_en: "Recurrent and persistent haematuria" },
  { code: "N03.9", name_zh: "慢性腎炎症候群", name_en: "Chronic nephritic syndrome, unspecified morphological changes" },
  { code: "N04.9", name_zh: "腎病症候群", name_en: "Nephrotic syndrome, unspecified" },
  { code: "N13.5", name_zh: "腎積水（伴有輸尿管阻塞）", name_en: "Crossing vessel and stricture of ureter without hydronephrosis" },
  { code: "N17.9", name_zh: "急性腎衰竭", name_en: "Acute kidney failure, unspecified" },
  { code: "N18.3", name_zh: "慢性腎臟病第三期", name_en: "Chronic kidney disease, stage 3" },
  { code: "N18.4", name_zh: "慢性腎臟病第四期", name_en: "Chronic kidney disease, stage 4" },
  { code: "N18.5", name_zh: "慢性腎臟病第五期", name_en: "Chronic kidney disease, stage 5" },
  { code: "N18.6", name_zh: "末期腎臟病（需透析）", name_en: "End stage renal disease" },
  { code: "N18.9", name_zh: "慢性腎臟病", name_en: "Chronic kidney disease, unspecified" },
  { code: "N20.0", name_zh: "腎結石", name_en: "Calculus of kidney" },
  { code: "N20.1", name_zh: "輸尿管結石", name_en: "Calculus of ureter" },
  { code: "N20.9", name_zh: "腎及輸尿管結石", name_en: "Urinary calculus, unspecified" },
  { code: "N23", name_zh: "腎絞痛", name_en: "Unspecified renal colic" },
  { code: "N28.1", name_zh: "腎囊腫", name_en: "Cyst of kidney, acquired" },
  { code: "N30.0", name_zh: "急性膀胱炎", name_en: "Acute cystitis" },
  { code: "N30.1", name_zh: "間質性膀胱炎", name_en: "Interstitial cystitis (chronic)" },
  { code: "N30.9", name_zh: "膀胱炎", name_en: "Cystitis, unspecified" },
  { code: "N39.0", name_zh: "泌尿道感染", name_en: "Urinary tract infection, site not specified" },
  { code: "N39.3", name_zh: "應激性尿失禁", name_en: "Stress incontinence (female)(male)" },
  { code: "N40", name_zh: "攝護腺肥大", name_en: "Enlarged prostate" },
  { code: "N41.0", name_zh: "急性攝護腺炎", name_en: "Acute prostatitis" },
  { code: "N41.1", name_zh: "慢性攝護腺炎", name_en: "Chronic prostatitis" },
  { code: "N43.3", name_zh: "睪丸鞘膜積液", name_en: "Hydrocele, unspecified" },
  { code: "N45.9", name_zh: "睪丸炎及附睪炎", name_en: "Orchitis, epididymitis and epididymo-orchitis" },
  { code: "N46", name_zh: "男性不孕症", name_en: "Male infertility" },
  { code: "N48.1", name_zh: "陰莖炎", name_en: "Balanoposthitis" },
  { code: "N52.9", name_zh: "勃起功能障礙", name_en: "Male erectile dysfunction, unspecified" },
  { code: "N63", name_zh: "乳房未特指腫塊", name_en: "Unspecified lump in breast" },
  { code: "N70.9", name_zh: "輸卵管炎及卵巢炎", name_en: "Salpingitis and oophoritis, unspecified" },
  { code: "N76.0", name_zh: "急性陰道炎", name_en: "Acute vaginitis" },
  { code: "N80.0", name_zh: "子宮內膜異位症（子宮）", name_en: "Endometriosis of uterus" },
  { code: "N92.0", name_zh: "月經過多及頻繁（規則週期）", name_en: "Excessive and frequent menstruation with regular cycle" },
  { code: "N94.3", name_zh: "原發性痛經", name_en: "Primary dysmenorrhoea" },
  { code: "N95.1", name_zh: "更年期及女性更年期狀態", name_en: "Menopausal and female climacteric states" },
  { code: "N97.9", name_zh: "女性不孕症", name_en: "Female infertility, unspecified" },
  // 妊娠相關
  { code: "O03.9", name_zh: "自然流產", name_en: "Complete or unspecified spontaneous abortion without complication" },
  { code: "O09.9", name_zh: "妊娠週數", name_en: "Supervision of high-risk pregnancy, unspecified" },
  { code: "O10.0", name_zh: "妊娠前即有之高血壓性心臟病", name_en: "Pre-existing essential hypertension complicating pregnancy, childbirth and the puerperium" },
  { code: "O14.1", name_zh: "嚴重子癲前症", name_en: "Severe pre-eclampsia" },
  { code: "O15.0", name_zh: "妊娠子癲症", name_en: "Eclampsia in pregnancy" },
  { code: "O24.4", name_zh: "妊娠糖尿病", name_en: "Gestational diabetes mellitus" },
  { code: "O26.6", name_zh: "肝臟疾病於妊娠中", name_en: "Liver and biliary tract disorders in pregnancy" },
  { code: "O42.0", name_zh: "胎膜早破（分娩開始前37週內）", name_en: "Premature rupture of membranes, onset of labour within 24 hours of rupture" },
  { code: "O60.1", name_zh: "早產分娩", name_en: "Preterm spontaneous labour with preterm delivery" },
  { code: "O80", name_zh: "自然分娩", name_en: "Single spontaneous delivery" },
  // 新生兒及兒科疾病
  { code: "P07.1", name_zh: "低出生體重兒", name_en: "Other low birth weight newborn" },
  { code: "P07.3", name_zh: "早產兒", name_en: "Other preterm newborn" },
  { code: "P22.0", name_zh: "新生兒呼吸窘迫症候群", name_en: "Respiratory distress syndrome of newborn" },
  { code: "P28.5", name_zh: "新生兒呼吸衰竭", name_en: "Respiratory failure of newborn" },
  { code: "P36.9", name_zh: "新生兒細菌性敗血症", name_en: "Bacterial sepsis of newborn, unspecified" },
  { code: "P59.9", name_zh: "新生兒黃疸", name_en: "Neonatal jaundice, unspecified" },
  // 先天性疾病
  { code: "Q05.9", name_zh: "脊柱裂", name_en: "Spina bifida, unspecified" },
  { code: "Q20.3", name_zh: "心室中膈缺損", name_en: "Discordant ventriculoarterial connection" },
  { code: "Q21.0", name_zh: "心室中隔缺損（VSD）", name_en: "Ventricular septal defect" },
  { code: "Q21.1", name_zh: "心房中隔缺損（ASD）", name_en: "Atrial septal defect" },
  { code: "Q25.0", name_zh: "開放性動脈導管", name_en: "Patent ductus arteriosus" },
  { code: "Q90.9", name_zh: "唐氏症", name_en: "Down syndrome, unspecified" },
  // 急診/外傷
  { code: "R00.0", name_zh: "心跳過速", name_en: "Tachycardia, unspecified" },
  { code: "R00.1", name_zh: "心跳過緩", name_en: "Bradycardia, unspecified" },
  { code: "R04.2", name_zh: "咳血", name_en: "Haemoptysis" },
  { code: "R05", name_zh: "咳嗽", name_en: "Cough" },
  { code: "R06.0", name_zh: "呼吸困難", name_en: "Dyspnoea" },
  { code: "R06.2", name_zh: "喘鳴聲", name_en: "Wheezing" },
  { code: "R07.4", name_zh: "胸痛", name_en: "Chest pain, unspecified" },
  { code: "R09.0", name_zh: "窒息", name_en: "Asphyxia" },
  { code: "R10.9", name_zh: "腹痛", name_en: "Unspecified abdominal pain" },
  { code: "R11.0", name_zh: "噁心", name_en: "Nausea" },
  { code: "R11.2", name_zh: "噁心合併嘔吐", name_en: "Nausea with vomiting, unspecified" },
  { code: "R17", name_zh: "黃疸", name_en: "Unspecified jaundice" },
  { code: "R19.7", name_zh: "腹瀉", name_en: "Diarrhoea, unspecified" },
  { code: "R21", name_zh: "皮疹（不特指）", name_en: "Rash and other nonspecific skin eruption" },
  { code: "R25.2", name_zh: "痙攣及抽搐", name_en: "Cramp and spasm" },
  { code: "R26.8", name_zh: "行走障礙", name_en: "Other abnormalities of gait and mobility" },
  { code: "R29.6", name_zh: "跌倒傾向", name_en: "Repeated falls" },
  { code: "R41.3", name_zh: "記憶力障礙", name_en: "Other amnesia" },
  { code: "R42", name_zh: "頭暈及暈眩", name_en: "Dizziness and giddiness" },
  { code: "R51", name_zh: "頭痛", name_en: "Headache" },
  { code: "R53.1", name_zh: "虛弱", name_en: "Weakness" },
  { code: "R55", name_zh: "暈厥", name_en: "Syncope and collapse" },
  { code: "R56.0", name_zh: "熱性痙攣", name_en: "Febrile convulsions" },
  { code: "R57.0", name_zh: "心因性休克", name_en: "Cardiogenic shock" },
  { code: "R57.9", name_zh: "休克", name_en: "Shock, unspecified" },
  { code: "R58", name_zh: "出血", name_en: "Haemorrhage, not elsewhere classified" },
  { code: "R73.0", name_zh: "血糖異常", name_en: "Abnormal glucose" },
  { code: "R73.9", name_zh: "高血糖", name_en: "Hyperglycaemia, unspecified" },
  { code: "R79.8", name_zh: "其他異常血液化學檢驗", name_en: "Other specified abnormal findings of blood chemistry" },
  // 外傷
  { code: "S00.0", name_zh: "頭皮表淺傷", name_en: "Superficial injury of scalp" },
  { code: "S01.0", name_zh: "頭皮傷口", name_en: "Open wound of scalp" },
  { code: "S02.0", name_zh: "顱骨骨折", name_en: "Fracture of vault of skull" },
  { code: "S06.0", name_zh: "腦震盪", name_en: "Concussion" },
  { code: "S06.3", name_zh: "腦挫傷", name_en: "Focal traumatic brain injury" },
  { code: "S12.9", name_zh: "頸椎骨折", name_en: "Fracture of cervical vertebra, unspecified" },
  { code: "S22.0", name_zh: "胸椎骨折", name_en: "Fracture of thoracic vertebra" },
  { code: "S22.4", name_zh: "肋骨骨折", name_en: "Multiple fractures of ribs" },
  { code: "S27.0", name_zh: "外傷性氣胸", name_en: "Traumatic pneumothorax" },
  { code: "S27.1", name_zh: "外傷性血胸", name_en: "Traumatic haemothorax" },
  { code: "S32.0", name_zh: "腰椎骨折", name_en: "Fracture of lumbar vertebra" },
  { code: "S32.5", name_zh: "恥骨骨折", name_en: "Fracture of pubis" },
  { code: "S42.0", name_zh: "鎖骨骨折", name_en: "Fracture of clavicle" },
  { code: "S42.2", name_zh: "上臂骨折", name_en: "Fracture of upper end of humerus" },
  { code: "S42.3", name_zh: "肱骨骨幹骨折", name_en: "Fracture of shaft of humerus" },
  { code: "S52.5", name_zh: "橈骨遠端骨折", name_en: "Fracture of lower end of radius" },
  { code: "S52.6", name_zh: "橈骨及尺骨下端骨折", name_en: "Fracture of lower end of both ulna and radius" },
  { code: "S72.0", name_zh: "股骨頸骨折", name_en: "Fracture of femoral neck" },
  { code: "S72.1", name_zh: "股骨粗隆間骨折", name_en: "Pertrochanteric fracture" },
  { code: "S72.9", name_zh: "股骨骨折", name_en: "Fracture of femur, unspecified" },
  { code: "S82.1", name_zh: "脛骨近端骨折", name_en: "Fracture of upper end of tibia" },
  { code: "S82.6", name_zh: "腳踝骨折", name_en: "Fracture of lateral malleolus" },
  { code: "S83.2", name_zh: "半月板撕裂傷", name_en: "Tear of meniscus, current" },
  { code: "S93.4", name_zh: "腳踝扭傷", name_en: "Sprain of ligaments of ankle" },
  // 中毒及過敏
  { code: "T14.0", name_zh: "體表傷口（部位未特指）", name_en: "Superficial injury of unspecified body region" },
  { code: "T14.1", name_zh: "開放性傷口（部位未特指）", name_en: "Open wound of unspecified body region" },
  { code: "T36.9", name_zh: "全身性抗生素中毒", name_en: "Poisoning by systemic antibiotics, unspecified" },
  { code: "T39.1", name_zh: "水楊酸中毒", name_en: "Poisoning by 4-Aminophenol derivatives" },
  { code: "T45.0", name_zh: "抗過敏藥物中毒", name_en: "Poisoning by antiallergic and antiemetic drugs" },
  { code: "T51.0", name_zh: "乙醇中毒", name_en: "Toxic effects of ethanol" },
  { code: "T58", name_zh: "一氧化碳中毒", name_en: "Toxic effect of carbon monoxide" },
  { code: "T78.0", name_zh: "食物過敏反應（過敏性休克）", name_en: "Anaphylactic reaction due to adverse food reaction" },
  { code: "T78.2", name_zh: "過敏性休克", name_en: "Anaphylactic shock, unspecified" },
  { code: "T78.4", name_zh: "過敏", name_en: "Allergy, unspecified" },
  // 外科術後
  { code: "T81.0", name_zh: "術後出血", name_en: "Haemorrhage and haematoma complicating a procedure" },
  { code: "T81.4", name_zh: "術後感染", name_en: "Infection following a procedure" },
  { code: "T82.8", name_zh: "心臟及血管裝置的其他並發症", name_en: "Other specified complications of cardiac and vascular prosthetic devices" },
  { code: "T84.0", name_zh: "骨科植入物的機械性並發症", name_en: "Mechanical complication of internal joint prosthesis" },
  // 其他疾病及補充代碼
  { code: "U07.1", name_zh: "COVID-19（病毒已確認）", name_en: "COVID-19, virus identified" },
  { code: "U07.2", name_zh: "COVID-19（病毒未確認）", name_en: "COVID-19, virus not identified" },
  { code: "Z00.0", name_zh: "健康檢查（一般）", name_en: "Encounter for general examination" },
  { code: "Z03.8", name_zh: "排除其他疾病的觀察", name_en: "Observation for other suspected diseases and conditions ruled out" },
  { code: "Z04.8", name_zh: "其他特定原因的檢查", name_en: "Encounter for examination and observation for other specified reasons" },
  { code: "Z12.1", name_zh: "結直腸癌篩查", name_en: "Encounter for screening for malignant neoplasm of intestinal tract" },
  { code: "Z13.0", name_zh: "貧血篩查", name_en: "Encounter for screening for anaemia" },
  { code: "Z21", name_zh: "HIV感染無症狀狀態", name_en: "Asymptomatic human immunodeficiency virus [HIV] infection status" },
  { code: "Z23", name_zh: "疫苗接種", name_en: "Encounter for immunization" },
  { code: "Z41.0", name_zh: "毛髮移植", name_en: "Encounter for hair transplantation" },
  { code: "Z43.1", name_zh: "胃造口護理", name_en: "Encounter for attention to gastrostomy" },
  { code: "Z48.0", name_zh: "外科傷口敷料換藥", name_en: "Encounter for change or removal of nonsurgical wound dressing" },
  { code: "Z51.0", name_zh: "化學治療", name_en: "Encounter for antineoplastic chemotherapy" },
  { code: "Z51.1", name_zh: "放射治療", name_en: "Encounter for antineoplastic radiation therapy" },
  { code: "Z79.4", name_zh: "長期使用胰島素", name_en: "Long term (current) use of insulin" },
  { code: "Z87.3", name_zh: "過去有藥物濫用病史", name_en: "Personal history of other endocrine, nutritional and metabolic diseases" },
  { code: "Z91.0", name_zh: "過敏史（藥物除外）", name_en: "Allergy status to foods, other than adverse food reactions" },
  { code: "Z92.1", name_zh: "長期使用抗凝血藥物史", name_en: "Personal history of long-term (current) use of anticoagulants" },
  { code: "Z96.6", name_zh: "髖關節人工關節植入物", name_en: "Presence of orthopaedic joint implants" },
  { code: "Z99.2", name_zh: "腎透析依賴", name_en: "Dependence on renal dialysis" },
  // 補充神經/精神
  { code: "G00.9", name_zh: "細菌性腦膜炎", name_en: "Bacterial meningitis, unspecified" },
  { code: "G03.9", name_zh: "腦膜炎", name_en: "Meningitis, unspecified" },
  { code: "G04.9", name_zh: "腦炎及腦脊髓炎", name_en: "Encephalitis and encephalomyelitis, unspecified" },
  { code: "G10", name_zh: "亨丁頓氏舞蹈症", name_en: "Huntington disease" },
  { code: "G12.2", name_zh: "運動神經元疾病", name_en: "Motor neuron disease" },
  { code: "G37.3", name_zh: "急性橫斷性脊髓炎", name_en: "Acute transverse myelitis in demyelinating disease of central nervous system" },
  { code: "G62.9", name_zh: "多發性神經病變", name_en: "Polyneuropathy, unspecified" },
  { code: "G70.0", name_zh: "重症肌無力", name_en: "Myasthenia gravis" },
  { code: "G71.0", name_zh: "肌肉失養症", name_en: "Muscular dystrophy" },
  { code: "G72.9", name_zh: "肌肉病變", name_en: "Myopathy, unspecified" },
  // 補充循環/心臟
  { code: "I05.0", name_zh: "二尖瓣狹窄", name_en: "Mitral stenosis" },
  { code: "I06.0", name_zh: "主動脈瓣逆流", name_en: "Rheumatic aortic stenosis" },
  { code: "I27.0", name_zh: "原發性肺動脈高壓", name_en: "Primary pulmonary hypertension" },
  { code: "I27.2", name_zh: "繼發性肺動脈高壓", name_en: "Other secondary pulmonary hypertension" },
  { code: "I31.3", name_zh: "心包積液", name_en: "Pericardial effusion (noninflammatory)" },
  { code: "I33.0", name_zh: "急性感染性心內膜炎", name_en: "Acute and subacute infective endocarditis" },
  { code: "I38", name_zh: "心瓣膜炎", name_en: "Endocarditis, valve unspecified" },
  { code: "I77.1", name_zh: "動脈狹窄", name_en: "Stricture of artery" },
  // 補充消化
  { code: "K11.5", name_zh: "唾液腺結石", name_en: "Salivary gland stone" },
  { code: "K56.0", name_zh: "腸麻痺性腸阻塞", name_en: "Paralytic ileus" },
  { code: "K56.2", name_zh: "腸套疊", name_en: "Volvulus" },
  { code: "K63.1", name_zh: "腸穿孔", name_en: "Perforation of intestine" },
  // 補充泌尿生殖
  { code: "N10", name_zh: "急性腎盂腎炎", name_en: "Acute pyelonephritis" },
  { code: "N11.0", name_zh: "慢性腎盂腎炎", name_en: "Chronic obstructive pyelonephritis" },
  { code: "N35.0", name_zh: "尿道狹窄（外傷後）", name_en: "Post-traumatic urethral stricture" },
  { code: "N47.1", name_zh: "包皮過長", name_en: "Phimosis" },
  { code: "N60.1", name_zh: "瀰漫性乳腺囊腫", name_en: "Diffuse cystic mastopathy" },
  { code: "N73.0", name_zh: "急性骨盆腔炎", name_en: "Acute parametritis and pelvic cellulitis" },
  { code: "N83.2", name_zh: "卵巢囊腫", name_en: "Other and unspecified ovarian cysts" },
  { code: "N90.0", name_zh: "外陰上皮內新生物", name_en: "Mild vulvar dysplasia" },
  { code: "N93.0", name_zh: "排卵後出血", name_en: "Postcoital and contact bleeding" },
  // 補充肌骨
  { code: "M00.9", name_zh: "感染性關節炎", name_en: "Pyogenic arthritis, unspecified" },
  { code: "M23.2", name_zh: "韌帶損傷（膝）", name_en: "Derangement of meniscus due to old tear or injury" },
  { code: "M43.1", name_zh: "脊椎滑脫", name_en: "Spondylolisthesis" },
  { code: "M60.0", name_zh: "感染性肌炎", name_en: "Infective myositis" },
  { code: "M72.2", name_zh: "蹠筋膜炎", name_en: "Plantar fascial fibromatosis" },
  { code: "M87.0", name_zh: "股骨頭缺血性壞死", name_en: "Idiopathic aseptic necrosis of bone" },
  // 補充兒科
  { code: "J05.0", name_zh: "急性阻塞性喉炎（哮吼）", name_en: "Acute obstructive laryngitis [croup]" },
  { code: "J21.9", name_zh: "急性細支氣管炎", name_en: "Acute bronchiolitis, unspecified" },
  { code: "L21.1", name_zh: "脂漏性嬰兒皮膚炎", name_en: "Seborrhoeic infantile dermatitis" },
];

